pretrained_codec_path: "descript/dac_16khz"
data_path_hf_hub: "JacobLinCool/VoiceBank-DEMAND-16k"
batch_size: 64
accumulate_grad_batches: 1
learning_rate: 1e-3
log_every_n_steps: 10
val_check_interval: 0.5
max_epochs: 10