pretrained_codec_path: "descript/dac_16khz"
denoiser_type: "mlp"
data_path_hf_hub: "JacobLinCool/VoiceBank-DEMAND-16k"

batch_size: 16
accumulate_grad_batches: 1
learning_rate: 1e-3
max_epochs: 2
limit_train_batches: 50
limit_val_batches: 2
limit_test_batches: 2

hf_hub_entity: "gokulkarthik"
log_every_n_steps: 10
val_check_interval: 0.25
