pretrained_codec_path: "descript/dac_16khz"
data_path_hf_hub: "JacobLinCool/VoiceBank-DEMAND-16k"
batch_size: 4
learning_rate: 1e-4
limit_train_batches: 100
limit_val_batches: 10
limit_test_batches: 10
log_every_n_steps: 10
max_epochs: 10